"""
Create Modbus Device File
=========================
Read a device list from an Excel sheet and generate a ready-to-run Ignition
Gateway script-console snippet that creates the devices idempotently
(existing devices are skipped, failures are reported).

Excel columns (matched BY HEADER, so column order does not matter):
    deviceType   optional, default 'ModbusTcp'
    deviceName   required, must be unique
    hostname     required (IP or hostname)
    port         optional, default 502

Optional Modbus device-property columns (added to deviceProps only when the
column exists AND the cell has a value; blank cells fall back to Ignition's
own defaults):
    communicationTimeout             (int, ms)
    maxHoldingRegistersPerRequest    (int)
    maxInputRegistersPerRequest      (int)
    maxCoilsPerRequest               (int)
    maxDiscreteInputsPerRequest      (int)
    spanGaps                         (bool: TRUE/FALSE)
    reverseWordOrder                 (bool: TRUE/FALSE)
    zeroBasedAddressing2             (bool: TRUE/FALSE)

Usage:
    python CreateModbusDeviceFile.py "Device Configuration/EPMS_System_6A.xlsx"
    python CreateModbusDeviceFile.py EPMS_System_6A.xlsx            # found under Device Configuration/
    python CreateModbusDeviceFile.py EPMS_System_6A.xlsx out.py     # explicit output path

Then open the generated .py and paste its contents into the Ignition
script console.  Requires: pandas, openpyxl.
"""

import os
import argparse

import pandas as pd

DEFAULT_DEVICE_TYPE = "ModbusTcp"
DEFAULT_PORT = 502
LOOKUP_DIR = "Device Configuration"

# Optional device props -> (Excel column, deviceProps key, value type).
# The column and key are usually identical; they differ only where the Excel
# header and the actual Ignition property key don't match.
# Included in deviceProps only when the column exists and the cell is non-blank.
OPTIONAL_PROPS = [
    ("communicationTimeout", "communicationTimeout", "int"),
    ("maxHoldingRegistersPerRequest", "maxHoldingRegistersPerRequest", "int"),
    ("maxInputRegistersPerRequest", "maxInputRegistersPerRequest", "int"),
    ("maxCoilsPerRequest", "maxCoilsPerRequest", "int"),
    ("maxDiscreteInputsPerRequest", "maxDiscreteInputsPerRequest", "int"),
    ("spanGaps", "spanGaps", "bool"),
    ("reverseWordOrder", "reverseWordOrder", "bool"),
    # Excel column keeps the '2'; emit the key WITHOUT it (testing which Ignition accepts).
    ("zeroBasedAddressing2", "zeroBasedAddressing", "bool"),
]

# The generated snippet targets Ignition's Jython 2.7 console (note: `print x`
# statement, not print()).  It is written as text only -- never executed here.
SCRIPT_HEAD = '''# Auto-generated by CreateModbusDeviceFile.py
# Source: {source}   |   Mode: {mode}
# Paste this entire script into an Ignition Gateway script console and run it.

devices = [
{device_lines}
]

existing = []
for row in system.device.listDevices():
    existing.append(row[0])

results = []
'''

# add mode: create new devices only; existing ones are left untouched.
LOOP_ADD = '''for device in devices:
    deviceName = device['deviceName']
    if deviceName in existing:
        results.append("%s: SKIPPED (already exists)" % deviceName)
        continue
    try:
        system.device.addDevice(deviceType=device['deviceType'],
                                 deviceName=deviceName,
                                 deviceProps=device['deviceProps'])
        results.append("%s: ADDED" % deviceName)
    except Exception as e:
        results.append("%s: FAILED - %s" % (deviceName, str(e)))
'''

# update mode: existing devices are REMOVED and re-added so property changes
# (e.g. zeroBasedAddressing2) take effect. New devices are simply added.
LOOP_UPDATE = '''for device in devices:
    deviceName = device['deviceName']
    try:
        if deviceName in existing:
            system.device.removeDevice(deviceName)
            system.device.addDevice(deviceType=device['deviceType'],
                                    deviceName=deviceName,
                                    deviceProps=device['deviceProps'])
            results.append("%s: UPDATED (removed + re-added)" % deviceName)
        else:
            system.device.addDevice(deviceType=device['deviceType'],
                                    deviceName=deviceName,
                                    deviceProps=device['deviceProps'])
            results.append("%s: ADDED" % deviceName)
    except Exception as e:
        results.append("%s: FAILED - %s" % (deviceName, str(e)))
'''

SCRIPT_FOOT = '''
for result in results:
    print result
print "----------------------------------------"
print "%d processed, %d total in file" % (len(results), len(devices))
'''


def _clean(v):
    """Trimmed string, or '' for blanks/NaN."""
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return ""
    return str(v).strip()


def _to_int(v, default):
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return default
    try:
        return int(float(v))
    except (ValueError, TypeError):
        return default


def _to_int_opt(v):
    """Integer, or None if blank/invalid (so the device default is used)."""
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return None
    try:
        return int(float(v))
    except (ValueError, TypeError):
        return None


def _to_bool_opt(v):
    """True/False from common spreadsheet values, or None if blank/unclear."""
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return None
    if isinstance(v, bool):
        return v
    s = str(v).strip().lower()
    if s in ("true", "1", "yes", "y", "t"):
        return True
    if s in ("false", "0", "no", "n", "f"):
        return False
    return None


def load_devices(path):
    """Return (devices, warnings). Validates names/hostnames/ports."""
    df = pd.read_excel(path)
    df.columns = [str(c).strip() for c in df.columns]

    missing = {"deviceName", "hostname"} - set(df.columns)
    if missing:
        raise SystemExit(
            "ERROR: missing required column(s): %s\n       Found columns: %s"
            % (", ".join(sorted(missing)), ", ".join(df.columns)))

    devices, warnings, seen = [], [], {}
    # start=2 so the number lines up with the Excel row (row 1 = header)
    for excel_row, row in enumerate(df.itertuples(index=False), start=2):
        rec = row._asdict()
        name = _clean(rec.get("deviceName"))
        if not name:
            continue  # skip fully blank rows silently

        host = _clean(rec.get("hostname"))
        dtype = _clean(rec.get("deviceType")) or DEFAULT_DEVICE_TYPE
        port = _to_int(rec.get("port"), DEFAULT_PORT)

        if not host:
            warnings.append("row %d '%s': blank hostname -> SKIPPED" % (excel_row, name))
            continue
        if name in seen:
            warnings.append("row %d '%s': duplicate name (first seen row %d) -> SKIPPED"
                            % (excel_row, name, seen[name]))
            continue
        if not (1 <= port <= 65535):
            warnings.append("row %d '%s': unusual port %s (kept)" % (excel_row, name, port))

        seen[name] = excel_row
        props = {"hostname": host, "port": port}
        # add any optional Modbus props that are present and filled in
        for col, key, kind in OPTIONAL_PROPS:
            if col not in df.columns:
                continue
            val = _to_bool_opt(rec.get(col)) if kind == "bool" else _to_int_opt(rec.get(col))
            if val is not None:
                props[key] = val

        devices.append({
            "deviceType": dtype,
            "deviceName": name,
            "deviceProps": props,
        })
    return devices, warnings


def main():
    ap = argparse.ArgumentParser(
        description="Generate an Ignition device-creation script from an Excel device list.")
    ap.add_argument("input", help="Device .xlsx path (also looked up under '%s/')." % LOOKUP_DIR)
    ap.add_argument("output", nargs="?",
                    help="Output .py path (default: <input>_create_devices.py beside the input).")
    ap.add_argument("--mode", choices=["add", "update"], default="add",
                    help="add (default): create new devices, skip existing. "
                         "update: remove + re-add existing devices so property "
                         "changes take effect (brief connection drop per device).")
    args = ap.parse_args()

    path = args.input
    if not os.path.isfile(path):
        alt = os.path.join(LOOKUP_DIR, args.input)
        if os.path.isfile(alt):
            path = alt
        else:
            raise SystemExit("ERROR: file not found: %s" % args.input)

    devices, warnings = load_devices(path)
    for w in warnings:
        print("[WARN] " + w)
    if not devices:
        raise SystemExit("No valid devices found in %s" % path)

    out = args.output or os.path.splitext(path)[0] + "_create_devices.py"
    device_lines = ",\n".join("    " + repr(d) for d in devices)
    loop = LOOP_UPDATE if args.mode == "update" else LOOP_ADD
    script = (SCRIPT_HEAD.format(source=os.path.basename(path), mode=args.mode,
                                 device_lines=device_lines)
              + loop + SCRIPT_FOOT)
    with open(out, "w", encoding="utf-8") as f:
        f.write(script)

    print("[OK] %d device(s) [mode=%s] -> %s" % (len(devices), args.mode, out))
    if args.mode == "update":
        print("     NOTE: update mode REMOVES + re-adds existing devices "
              "(brief connection drop; props reset to what's in the sheet).")
    if warnings:
        print("     %d row(s) skipped/flagged (see warnings above)." % len(warnings))
    print("     Open it and paste the contents into the Ignition script console.")


if __name__ == "__main__":
    main()
