# Auto-generated by CreateModbusDeviceFile.py
# Source: Phase_1_Busway.xlsx   |   Mode: add
# Paste this entire script into an Ignition Gateway script console and run it.

devices = [
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6A-1', 'deviceProps': {'hostname': '172.24.248.207', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6A-2', 'deviceProps': {'hostname': '172.24.248.209', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6A-3', 'deviceProps': {'hostname': '172.24.248.211', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6A-4', 'deviceProps': {'hostname': '172.24.248.213', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6A-5', 'deviceProps': {'hostname': '172.24.248.109', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6A-6', 'deviceProps': {'hostname': '172.24.248.110', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6B-1', 'deviceProps': {'hostname': '172.24.248.208', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6B-2', 'deviceProps': {'hostname': '172.24.248.214', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6B-3', 'deviceProps': {'hostname': '172.24.248.216', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6B-4', 'deviceProps': {'hostname': '172.24.248.218', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6B-5', 'deviceProps': {'hostname': '172.24.248.231', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6B-6', 'deviceProps': {'hostname': '172.24.248.111', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6C-1', 'deviceProps': {'hostname': '172.24.248.210', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6C-2', 'deviceProps': {'hostname': '172.24.248.215', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6C-3', 'deviceProps': {'hostname': '172.24.248.220', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6C-4', 'deviceProps': {'hostname': '172.24.248.222', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6C-5', 'deviceProps': {'hostname': '172.24.248.228', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6D-1', 'deviceProps': {'hostname': '172.24.248.212', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6D-2', 'deviceProps': {'hostname': '172.24.248.217', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6D-3', 'deviceProps': {'hostname': '172.24.248.221', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6D-4', 'deviceProps': {'hostname': '172.24.248.224', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6D-5', 'deviceProps': {'hostname': '172.24.248.229', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6E-1', 'deviceProps': {'hostname': '172.24.250.224', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6E-2', 'deviceProps': {'hostname': '172.24.248.219', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6E-3', 'deviceProps': {'hostname': '172.24.248.223', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6E-4', 'deviceProps': {'hostname': '172.24.248.225', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6E-5', 'deviceProps': {'hostname': '172.24.248.230', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'BUS-6E-6', 'deviceProps': {'hostname': '172.24.248.112', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': True, 'zeroBasedAddressing': False}}
]

existing = []
for row in system.device.listDevices():
    existing.append(row[0])

results = []
for device in devices:
    deviceName = device['deviceName']
    if deviceName in existing:
        results.append("%s: SKIPPED (already exists)" % deviceName)
        continue
    try:
        system.device.addDevice(deviceType=device['deviceType'],
                                 deviceName=deviceName,
                                 deviceProps=device['deviceProps'])
        results.append("%s: ADDED" % deviceName)
    except Exception as e:
        results.append("%s: FAILED - %s" % (deviceName, str(e)))

for result in results:
    print result
print "----------------------------------------"
print "%d processed, %d total in file" % (len(results), len(devices))
