# Auto-generated by CreateModbusDeviceFile.py
# Source: Phase_1_PQMs.xlsx   |   Mode: add
# Paste this entire script into an Ignition Gateway script console and run it.

devices = [
    {'deviceType': 'ModbusTcp', 'deviceName': 'SW6C_PQM', 'deviceProps': {'hostname': '172.24.250.110', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': False, 'zeroBasedAddressing': True}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'UP6C_PQM', 'deviceProps': {'hostname': '172.24.250.111', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': False, 'zeroBasedAddressing': True}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'ODP-6C_PQM', 'deviceProps': {'hostname': '172.24.250.127', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': False, 'zeroBasedAddressing': True}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'SW6D_PQM', 'deviceProps': {'hostname': '172.24.250.152', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': False, 'zeroBasedAddressing': True}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'UP6D_PQM', 'deviceProps': {'hostname': '172.24.250.153', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': False, 'zeroBasedAddressing': True}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'ODP-6D_PQM', 'deviceProps': {'hostname': '172.24.250.169', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': False, 'zeroBasedAddressing': True}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'SW6E_PQM', 'deviceProps': {'hostname': '172.24.250.194', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': False, 'zeroBasedAddressing': True}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'UP6E_PQM', 'deviceProps': {'hostname': '172.24.250.195', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': False, 'zeroBasedAddressing': True}},
    {'deviceType': 'ModbusTcp', 'deviceName': 'ODP-6E_PQM', 'deviceProps': {'hostname': '172.24.250.211', 'port': 502, 'communicationTimeout': 5000, 'maxHoldingRegistersPerRequest': 125, 'maxInputRegistersPerRequest': 125, 'maxCoilsPerRequest': 200, 'maxDiscreteInputsPerRequest': 200, 'spanGaps': True, 'reverseWordOrder': False, 'zeroBasedAddressing': True}}
]

existing = []
for row in system.device.listDevices():
    existing.append(row[0])

results = []
for device in devices:
    deviceName = device['deviceName']
    if deviceName in existing:
        results.append("%s: SKIPPED (already exists)" % deviceName)
        continue
    try:
        system.device.addDevice(deviceType=device['deviceType'],
                                 deviceName=deviceName,
                                 deviceProps=device['deviceProps'])
        results.append("%s: ADDED" % deviceName)
    except Exception as e:
        results.append("%s: FAILED - %s" % (deviceName, str(e)))

for result in results:
    print result
print "----------------------------------------"
print "%d processed, %d total in file" % (len(results), len(devices))
